# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='document/uploaded_file/')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=225)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=225)),
            ],
        ),
    ]
