# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('cell_group', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('baptism', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=225)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=225)),
            ],
        ),
    ]
