# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell_report',
            name='created_by',
            field=models.CharField(max_length=225, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cell_report',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='cell_report',
            name='report',
            field=models.FileField(upload_to='document/uploaded_file/', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='cell_report',
            name='updated_by',
            field=models.CharField(max_length=225, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='cell_report',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptism',
            field=models.BooleanField(default=False, verbose_name='Baptism'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cell_group',
            field=models.CharField(max_length=100, verbose_name='Cell Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.CharField(max_length=225, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_by',
            field=models.CharField(max_length=225, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
