# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-13 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181010_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell_report',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
